-- AlterTable
ALTER TABLE "Ingredient" ADD COLUMN "caloriesPer100g" DOUBLE PRECISION,
ADD COLUMN "proteinPer100g" DOUBLE PRECISION,
ADD COLUMN "carbsPer100g" DOUBLE PRECISION,
ADD COLUMN "fatPer100g" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "ProductReference" ADD COLUMN "caloriesPer100g" DOUBLE PRECISION,
ADD COLUMN "proteinPer100g" DOUBLE PRECISION,
ADD COLUMN "carbsPer100g" DOUBLE PRECISION,
ADD COLUMN "fatPer100g" DOUBLE PRECISION;
